### PR TITLE
Add dependency to knockout.validation instead of knockout.

### LINKED ISSUE #509: Localization loading randomly breaks when using requirejs
It is not currently possible to configure a general requirejs dependency rule that covers all current and future localizations, and since the localization only tells requirejs it depends on knockout, the loading randomly breaks.

### PR DESCRIPTION
**Pull request by ViceIce**
Closes #509

### CODE REVIEW

**Comment by crissdev** [comment]
Looks good. :+1: 
Once I have some time for it will merge it.

**Comment by ViceIce** [comment]
Should i squash the commits?

**Comment by crissdev** [comment]
If you want to, sure. It will speed up things. You may also want to replace `knockout` with `knockout-validation` on lines 8 and 11 :-)

**Comment by ViceIce** [comment]
ok, i will do it.

**Comment by ViceIce** [comment]
Like this?

**Comment by crissdev** [comment]
Yeap. To further prevent a rebase on my end, please rebase you last commit (reword) and change the commit message to just "Fix #509 - Localization loading randomly breaks when using requirejs" - to make it similar to other commits. And that should be it.

**Comment by ViceIce** [comment]
Ok. :smile:

**Comment by crissdev** [comment]
Thanks a lot.

For upcoming releases it worths checking out https://github.com/Knockout-Contrib/Knockout-Validation/milestones

**Comment by ViceIce** [comment]
No problem. :+1:

**Pull request merged**
