### PR TITLE
Add ability to dynamically change the language when using requirejs

### PR DESCRIPTION
**Pull request by davhdavh**
doc added:

Alternatively, you can use require.js and do like this.
**Note** On the first load of the file, the language is automatically changed to the new language.

```javascript
require(['PATH_TO_KNOCKOUT_VALIDATION/localization/'+iso], function(dynLanguageChange){
	dynLanguageChange(); //language changed
	})
```

### CODE REVIEW

**Comment by davhdavh** [comment]
How do I make it forget the already merged things about the html5-attributes?

**Comment by crissdev** [comment]
Most probably the cause is because I amended your commit when it was merged. I'm not really sure how Github will react but you can try the following:

0. Export your changes as a patch
1. Reset your fork to 72ae9aa11aad009e57aaeae7ca41db878dfcfce7 (git reset --hard <sha1> http://stackoverflow.com/questions/1616957/how-do-you-roll-back-reset-a-git-repository-to-a-particular-commit)
2. Apply your changes and push to repository with force option (http://stackoverflow.com/questions/10510462/force-git-push-to-overwrite-remote-files)

If this won't work then you'll just make another PR but after forking the repository again so you're in sync.

**Comment by crissdev** [comment]
Moreover, please add a `Closing #492` command for you commit since I will be reopening that issue. Thanks.

**Comment by davhdavh** [comment]
It will merge fine though, just the history that is a bit messed up.

**Comment by crissdev** [comment]
As for the `README.md` file update please change it to something similar in the `Localization` section - make it particular, not generic. It will be easier to understand the usage with RequireJS.

**Comment by davhdavh** [comment]
reset doesnt work

 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/davhdavh/Knockout-Validation.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by crissdev** [comment]
The more I look into this the more I think we should refactor this to become more usable.

The cons:

* No easy way to change language when not using AMD (it would be possible only by loading on demand the localization script)
* When loading the localization file it's automatically applying the localization. This means that loading multiple scripts will result in undefined behaviour due to AMD loader loading scripts async and not in a specific order.

I could add more to this but instead I want to propose a solution. I suggest to go for something similar to moment.js but simplified:

* every localization script should invoke a `ko.validation.defineLocale` method that registers the localization for a particul language.
* `ko.validation.defineLocale` would maintain a dictionary of loaded languages
* define a `ko.validation.locale` to switch localization
* the current `ko.validation.localize` can be used to apply the new locales.

This would also resolve the issue of switching locales when not using AMD.

What do you think?

**Comment by davhdavh** [comment]
The problem is that not setting the language after loading does 2 things.
First it breaks all existing script, second it is not obvious and thus
makes it harder to use the validation.

Furthermore, it doesn't really solve the async loading problem. The
solution people then usually choose is to simple load ALL languages even if
they only need 2, which just means longer  loading.

**Comment by crissdev** [comment]
I somewhat agree regarding the breaking change but localization files could not really be used with RequireJS without some pre-processing. Since a major version will be released I would prefer the future benefits than having backward compatibility.

The real benefit I see in going on this path is that it allows:

* inserting `script` tags for all languages you want to use
* possibility for the library to create custom builds - localization bundle, library+localization
* **no** unexpected behavior when loading multiple localization files (AMD or whatever)
* consistency in loading and applying localizations - I don't like the fact that first load applies the localization, then I must invoke a method.

Here is some sample usage:

**no AMD**

```html
<head>
   <script src="knockout.validation.js"></script>
   <script src="localization/en-US.js"></script>
   <script src="localization/de-DE.js"></script>
</head>

<body>
    <script>
        ko.validation.locale('en-US');

        // later
        ko.validation.locale('de-DE');
    </script>
</body>
```

**AMD**

```js
define(['knockout-validation', 'localization/en-US', 'localization/de-DE.js'], 
function(kv) {
    kv.locale('en-US');

    // or
    kv.locale('de-DE');
});
```

or

```js
define(['knockout-validation', 'localization-bundle.js'], function(kv) {
    kv.locale('en-US');

    // or
    kv.locale('de-DE');
});


```

**Comment by davhdavh** [comment]
I didnt make it possible to load individual languages, but all it requires is a bit of gruntfile setup.

**Comment by crissdev** [comment]
Thanks @davhdavh 

These commits really put me in a difficult spot. I'm aware we didn't have a complete spec for this and I'll try to be as gentle as possible :-)

Here's my suggestions / oppinions related to this PR.

* There's no reason to bump the version and add it to the file name
    - The new version will be `2.0.0`. We also don't push `pre-releases` in Knockout-Validation `Releases` - we might do that in the future.
    - The `Dist` directory will contain the output file for the current branch and not for specific versions. The only place the version will be included in the file name is in the NuGet package.

* `Dist/Knockout-Validation.nuspec` is a file which will either be moved in a separate branch or removed. The NuGet package information can be easily obtain through various methods. so there's no reason to change that file.
  - An automated script might be created for publishing and put in the new branch to make it easy to publish updates to Nuget - publishing is only possible by package owners though.
  - There's no real benefit of having that file in `Dist` directory for development/production environment.

* For localization related files you assume the ID of the library is `knockout-validation` which may be wrong in some deployments.
  - Since we don't have a fixed ID for AMD version this might fail
  - This will not work for NodeJS package - if you take a closer look in the `package.json` file you'll notice the `main` property set to `Dist/knockout.validation.js`, and `name` is set to `knockout.validation`.

* For `2.0` version I don't want to go that far with localization.
  - I don't think we should expose `ko.validation.localizations` for now.
  - Each localization file should be independent, and no `Grunt` involvement should be required for now.
  - Bundling will go in a 2.x.y version


Apart from that please take into consideration the following:

* the release for `2.0` will be available next week so there's no room for big changes anymore
* the structure will change a bit - all directories will be lowercase and the `Lib` directory will move. This is possible at this point because the current list of PR is short and there's nothing there left to merge for v2 and also not impossible to extract what's useful and integrate.

If you could rebase your commits and squash them it would be great.

**Comment by davhdavh** [comment]
* Version in filename. Ok

* Version bump. Needed since breaking change.

* Nuspec. I was just being consistent and updating it also.

* Require id. I added it in output, so that you CAN assume it is exists.
This is consistent with other major libs. If people have given it another
name they are still free to use that. And it is absolutely necessary to
ensure loading order for i18n when using require and not forcing people to
have to make manual dependency rules.

* Bundling. I feel it is better to break all existing scripts because the
logic changed and not supply individual files in 2.0. That way people will
notice it is a breaking change and not just update blind and assume it
works. I feel it is better that you later support individual language
files.

And I don't understand your last comment at all. What do you mean by rebase
and squash?

**Comment by crissdev** [comment]
[This plnk](http://plnkr.co/edit/SXJDZu46o9vCuk6P8icz?p=preview) really should make a point about the module ID.

**Comment by davhdavh** [comment]
I dont know what you mean by that plnk? You made a module named oh.wow, and you reference it by oh-wow...
http://plnkr.co/edit/KMcQFxMyoYsqTTqMTffW?p=preview
This is what I mean... Because jquery itself defined 'jquery' it does not matter what you call it in your config. After it is loaded, the definition 'jquery' is defined by jquery itself and can be used by any 3rd party (or by modules inside jquery itself) to get jquery.

**Comment by crissdev** [comment]
> After it is loaded, the definition

Exactly that's the problem the plnk was for.

Closing this PR for reasons available in my previous long comment.

**Comment by davhdavh** [comment]
Whatever... Dont expect more contributions from me

**Comment by crissdev** [comment]
I'm sorry to hear that.  

I tried to provide as much help and guidance as I could. Sometimes PRs just don't get the change to be merged.

As I said, the release is just a few days away and we must be quick to fix issues and let room for big changes in the next releases.

**Pull request closed without merging**
