### PR TITLE
Async imm

### PR DESCRIPTION
**Pull request by jhsowter**
Async rules that return immediately for some reason, for example caching, should not be cleared if they return false. Same as Async imm #538 but passes jslint.

### CODE REVIEW

**Comment by crissdev** [comment]
Thanks @jhsowter . Do you think you can squash all these commits into one?

---
FYI, when you make a PR subsequent commits go to it. Furthermore, if you decide to squash commits and forcely push the changes (to your fork), they will be picked up by the PR. There's no need to create new PRs.

**Comment by jhsowter** [comment]
OK. Is it better to squash to master or to the branch? I assume it doesn't matter.

**Comment by crissdev** [comment]
Since the PR is created from `jhsowter:async_imm` I think you should squash the commits on `async_imm` branch.

**Comment by jhsowter** [comment]
Great thanks for you help. I've done that now.

**Comment by crissdev** [comment]
@jhsowter Clearing the error before validating the observable will trigger unnecessary notifications. For instance, consider the following flow of events:
* observable is not valid
* observable changes and validation takes place
* _error is cleared thus making observable valid_
* during validation a rule marks the observable _invalid_

So the notifications raised by the item in _italic_ are unnecessary. This might not have a big perf impact but may cause problems when implementing animations for displaying messages when validation state changes.

Moreover, I ran the tests with the callback wrapped in an async call and the tests passed. I guess the failure you've encountered was due to the way you called `ko.utils.unwrapObservable` (taken from TravisCI build log) http://jsfiddle.net/ejcLdd4j/

**Comment by jhsowter** [comment]
Hi Christian

The failing test was due to an incorrect expectation that I could get isValid() == false at the bottom of the test, but if we use `utils.async` then that isn't true. So I removed this test. 

I did get the jslint problem from copying the dist version of the fix you suggested. 

So I have made the change you suggested and included just the one test. Sorry for the confusion.

**Comment by crissdev** [comment]
```js
ctx.params === undefined ? true : ko.utils.unwrapObservable(ctx.params)
```

The reason why that line has to be like that is because the following test will fail otherwise.

```js
QUnit.test('Async rule does not send correct params', function(assert) {
    var done = assert.async();
    assert.expect(1);

    ko.validation.rules['immediatelyFalse'] = {
        async: true,
        validator: function (val, params, callBack) {
            callBack(false);
            assert.strictEqual(params, 0, 'params is zeo');
            done();
        },
        message: 'this should be false.'
    };
    ko.validation.registerExtenders();

    var testObj = ko.observable(0);
    testObj.extend({ immediatelyFalse: 0 });
});
```

http://jsfiddle.net/9jowpxfa/

Now LGTM. No need to make further changes. Thanks for contributing.

**Comment by jhsowter** [comment]
Cool. I appreciate your help.

**Comment by crissdev** [comment]
landed in 52daa1050ca61b83a0c38eebdafe19f1f17465b1

**Pull request closed without merging**
