### PR TITLE
Fix for issue #519, unnecessary check for validatable observables

### PR DESCRIPTION
**Pull request by askheaves**
Fix for issue #519, unnecessary check for validatable observables with validationElement and validationMessage in markup.

https://github.com/Knockout-Contrib/Knockout-Validation/issues/519

### CODE REVIEW

**Comment by crissdev** [comment]
Thanks @askheaves 

Consider adding a few more tests and some assertions inside them. For instance:
* what happens if the observable becomes validatable
* what happens when validation is disposed (observable is extended with `{validatable: false}`)

**Comment by askheaves** [comment]
This is starting to turn out a bit nasty. I'm having trouble with making even a validatable object able to take validatable: false due to the disposing code (observable._disposeValidation). It seems to be accessing the private _subscriptions member of the observable, which isn't publicly available in KO 3.2.0. Here's a short repro with the issue:

    QUnit.test('Validatable can become non-validatable', 0, function(assert) {
      var vm = {
        testObj: ko.observable().extend({
          required: { params: true, message: "failing" }
        })
      };
      addTestHtml('<input type="text" id="testElement" data-bind="value: testObj, validationElement: testObj, validationMessage: testObj"/>');
      // make sure we allow element decorations
      ko.validation.init({ decorateInputElement: true }, true);
      applyTestBindings(vm);
      vm.testObj.extend({validatable: false});
    });

I'm not sure how to proceed with this outside my understanding of the internals.

**Comment by crissdev** [comment]
Confirmed. The `_disposeValidation` was added in be9a5f5b3020e0950da6246cb16b0e0e08ab69b6. What I don't understand is why the code attempts to change an internal (Knockout) field - the array of subscriptions. Furthermore it doesn't call `dispose` on the subscription. My conclusion is the library should dispose only subscriptions and computed it created and let Knockout do the rest of the cleanup. I will submit an issue around this and have it fixed.

**Comment by crissdev** [comment]
Fixed issue with disposing validation #526 
Consider pulling from master branch with `--rebase` option.

**Comment by askheaves** [comment]
Didn't quite figure out how to github correctly, so there's a new pull request here with additional unit tests.
https://github.com/Knockout-Contrib/Knockout-Validation/pull/529

**Comment by crissdev** [comment]
Next time you can `git pull --rebase origin master` and `git push origin master --force`. The PR will automatically pick up the new changes in your fork. The `--rebase` will avoid a merge commit and future conflicts when merging the PR.

**Pull request closed without merging**
