### PR TITLE
Add dependency to knockout.validation.

### LINKED ISSUE #509: Localization loading randomly breaks when using requirejs
It is not currently possible to configure a general requirejs dependency rule that covers all current and future localizations, and since the localization only tells requirejs it depends on knockout, the loading randomly breaks.

### PR DESCRIPTION
**Pull request by ViceIce**
Closes #509

### CODE REVIEW

**Comment by crissdev** [comment]
A few suggestions:

* remove dependency on `knockout`, and keep only `knockout.validation` (use `kv.defineLocale` instead)
* the factory method would receive a `kv` parameter in this case, so the current check should be changed against this parameter
* consier changing `knockout` to `knockout.validation` in the comments

Thanks.

**Comment by ViceIce** [comment]
ok

**Comment by crissdev** [comment]
:confused: Is there a reason for closing this PR?

**Comment by crissdev** [comment]
Just saw #517

**Comment by ViceIce** [comment]
I opened a new one #517.

Sorry.

**Comment by ViceIce** [comment]
I have to lewan how to add new commits to the pr. :innocent:

**Comment by crissdev** [comment]
No problem. FYI, when you make a PR subsequent commits go to it. Furthermore, if you decide to squash commits and forcely push the changes (to your fork), they will be picked up by the PR.

**Comment by ViceIce** [comment]
Cool, have not done this before. Next time i know it. :relaxed:

**Comment by crissdev** [comment]
:+1:

**Pull request closed without merging**
